name: "Nix"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
jobs:
  regenerate-index:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - name: Install nix
      uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Index packages
      run: nix run .#index
    - name: Translate locks
      continue-on-error: true
      run: JOBS=20 nix run .#translate
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore: regenerate index & lock files"
        branch: main
